database:
  host: 47.118.19.28
  port: 3307
  user: root
  password: sta_go
  database: durlim
  charset: utf8mb4

redis:
  addr: 47.118.19.28:6379      # Redis地址
  password: "sta_go"              # Redis密码，无密码留空
  db: 0                     # Redis数据库编号

server:
  port: 8080
  host: "0.0.0.0"

